### ISSUE TITLE
Folder pics reverse order

### ISSUE THREAD

**Issue by peregrau** [CodeBoy722/Android-Simple-Image-Gallery#1]
thanks Emmanuel,

this is not issue, I wold to know how reverse order of the pic folders array .

thanks a lot,

Pere

**Comment by CodeBoy722** [comment]
if I do well understand your problem, you want to reverse the order of the pic folders ArrayList the simplest way will be to create another ArrayList the populate it by doing a reverse iteration loop with the original ArrayList as the code below

       //reverse order ArrayList
        ArrayList<imageFolder> reverseFolders = new ArrayList<>();
        
        for(int i = picFolders.size()-1;i > reverseFolders.size()-1;i--){
            reverseFolders.add(picFolders.get(i));
        }

**Comment by peregrau** [comment]
Thanks. I 'll try it

El ds., 2 de nov. 2019, 2:38, Mofor Ndifor Emmanuel <
notifications@github.com> va escriure:

**Comment by CodeBoy722** [comment]
hope that helps you
